<a href="https://colab.research.google.com/github/juanfelipegonzalezalfonso/programacion1/blob/main/piton%20ni%20idea.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files # Para cargar archivos en google colab
uploaded = files.upload()

Saving f_capitulos.csv to f_capitulos.csv

In [18]:
import io
f_capitulos1 = io.BytesIO(uploaded['f_capitulos.csv'])
f_capitulos1 = pd.read_csv(f_capitulos1, sep = ",", encoding="latin-1")
f_capitulos1.head(4)

,F_01,F_01_CUAL,F_02,F_02_CUAL,F_03,F_04,F_05,F_06,F_07,F_08,...,F_18,F_19,F_20,F_20_CUAL,F_21,F_21_CUAL,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN
0,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,2
1,2,NaN,2,NaN,1,18.0,3.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,1,1,1
2,2,NaN,2,NaN,1,20.0,3.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,1,1,1
3,2,NaN,2,NaN,1,20.0,3.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4,1,1,1

In [19]:
tabla_alcohol = pd.DataFrame({
    'edad': f_capitulos1['F_04'],
    'borrachera': f_capitulos1['F_09'],
    'cerveza': f_capitulos1['F_10_A'],
    'recordar': f_capitulos1['F_19'],
    "preocupacion": f_capitulos1["F_21"]
    })
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  preocupacion
0   NaN         NaN      NaN       NaN           NaN
1  18.0         NaN      NaN       NaN           NaN
2  20.0         NaN      NaN       NaN           NaN
3  20.0         NaN      NaN       NaN           NaN
4  20.0         NaN      NaN       NaN           NaN

In [21]:
tabla_alcohol['cerveza'] = tabla_alcohol['cerveza'].fillna(0)
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  preocupacion
0   0.0         NaN      0.0       NaN           NaN
1  18.0         NaN      0.0       NaN           NaN
2  20.0         NaN      0.0       NaN           NaN
3  20.0         NaN      0.0       NaN           NaN
4  20.0         NaN      0.0       NaN           NaN

In [22]:
tabla_alcohol['borrachera'] = tabla_alcohol['borrachera'].fillna(0)
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  preocupacion
0   0.0         0.0      0.0       NaN           NaN
1  18.0         0.0      0.0       NaN           NaN
2  20.0         0.0      0.0       NaN           NaN
3  20.0         0.0      0.0       NaN           NaN
4  20.0         0.0      0.0       NaN           NaN

In [23]:
tabla_alcohol['recordar'] = tabla_alcohol['recordar'].fillna(0) # 0 lo tomaremos para quienes no consumen alcohol
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  preocupacion
0   0.0         0.0      0.0       0.0           NaN
1  18.0         0.0      0.0       0.0           NaN
2  20.0         0.0      0.0       0.0           NaN
3  20.0         0.0      0.0       0.0           NaN
4  20.0         0.0      0.0       0.0           NaN

In [24]:
tabla_alcohol['preocupacion'] = tabla_alcohol['borrachera'].fillna(2)
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  preocupacion
0   0.0         0.0      0.0       0.0           0.0
1  18.0         0.0      0.0       0.0           0.0
2  20.0         0.0      0.0       0.0           0.0
3  20.0         0.0      0.0       0.0           0.0
4  20.0         0.0      0.0       0.0           0.0

In [25]:
tabla_alcohol1 = tabla_alcohol.dropna()
tabla_alcohol1.head(5)

   edad  borrachera  cerveza  recordar  preocupacion
0   0.0         0.0      0.0       0.0           0.0
1  18.0         0.0      0.0       0.0           0.0
2  20.0         0.0      0.0       0.0           0.0
3  20.0         0.0      0.0       0.0           0.0
4  20.0         0.0      0.0       0.0           0.0

In [31]:
tabla_alcohol1['cerveza'] = tabla_alcohol1['cerveza'].astype(str)
tabla_alcohol1['recordar'] = tabla_alcohol1['recordar'].astype(str)
tabla_alcohol1['preocupacion'] = tabla_alcohol1['preocupacion'].astype(str)+